# Generated by Django 4.2.1 on 2023-05-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='Email',
            field=models.EmailField(max_length=280),
        ),
    ]
